### ISSUE TITLE
Error `TypeError: Cannot read property 'startsWith' of null`

### ISSUE THREAD

**Issue by ehmicky** [Munter/netlify-plugin-checklinks#189]
The following error happened in a specific build:

```
a promise was rejected but not handled: TypeError: Cannot read property 'startsWith' of null 
    /opt/buildhome/.netlify-build-plugins/node_modules/assetgraph/lib/relations/Relation.js:278:24 HtmlAnchor.get canonical [as canonical]
    /opt/buildhome/.netlify-build-plugins/node_modules/assetgraph/lib/relations/Relation.js:215:14 HtmlAnchor.get crossorigin [as crossorigin]
    /opt/buildhome/.netlify-build-plugins/node_modules/hyperlink/lib/index.js:640:25 processAsset
```

Full build logs:

```
7:24:10 AM: Build ready to start
7:24:12 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
7:24:12 AM: build-image tag: v3.4.1
7:24:12 AM: buildbot version: fcbc7a79f7372e5995cf02954ef19fc48d20c871
7:24:13 AM: Fetching cached dependencies
7:24:13 AM: Starting to download cache of 121.9MB
7:24:13 AM: Finished downloading cache in 739.034128ms
7:24:13 AM: Starting to extract cache
7:24:19 AM: Finished extracting cache in 5.743514597s
7:24:19 AM: Finished fetching cache in 6.526594691s
7:24:19 AM: Starting to prepare the repo for build
7:24:19 AM: Preparing Git Reference refs/heads/master
7:24:21 AM: Starting build script
7:24:21 AM: Installing dependencies
7:24:21 AM: Python version set to 2.7
7:24:21 AM: Started restoring cached node version
7:24:24 AM: Finished restoring cached node version
7:24:25 AM: v12.18.0 is already installed.
7:24:25 AM: Now using node v12.18.0 (npm v6.14.4)
7:24:25 AM: Started restoring cached build plugins
7:24:25 AM: Finished restoring cached build plugins
7:24:25 AM: Attempting ruby version 2.7.1, read from environment
7:24:27 AM: Using ruby version 2.7.1
7:24:27 AM: Using PHP version 5.6
7:24:27 AM: 5.2 is already installed.
7:24:27 AM: Using Swift version 5.2
7:24:27 AM: Started restoring cached node modules
7:24:27 AM: Finished restoring cached node modules
7:24:27 AM: Installing NPM modules using NPM version 6.14.4
7:24:32 AM: npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
7:24:36 AM: npm notice created a lockfile as package-lock.json. You should commit this file.
7:24:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
7:24:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:24:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/fork-ts-checker-webpack-plugin/node_modules/chokidar/node_modules/fsevents):
7:24:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:24:36 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/webpack/node_modules/chokidar/node_modules/fsevents):
7:24:36 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:24:36 AM: npm WARN enoent ENOENT: no such file or directory, open '/opt/build/repo/node_modules/@babel/plugin-syntax-object-rest-spread/node_modules/@babel/core/package.json'
7:24:36 AM: npm WARN enoent ENOENT: no such file or directory, open '/opt/build/repo/node_modules/lint-staged/node_modules/cross-spawn/package.json'
7:24:36 AM: npm WARN enoent ENOENT: no such file or directory, open '/opt/build/repo/node_modules/lpad-align/node_modules/redent/package.json'
7:24:36 AM: npm WARN enoent ENOENT: no such file or directory, open '/opt/build/repo/node_modules/prettier-eslint/node_modules/@typescript-eslint/experimental-utils/package.json'
7:24:36 AM: npm WARN @next/react-dev-overlay@9.4.4 requires a peer of react@^16.9.0 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN @next/react-dev-overlay@9.4.4 requires a peer of react-dom@^16.9.0 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN goober@2.0.5 requires a peer of csstype@^2.6.2 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN next@9.4.4 requires a peer of react@^16.6.0 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN next@9.4.4 requires a peer of react-dom@^16.6.0 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN styled-jsx@3.3.0 requires a peer of react@15.x.x || 16.x.x but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN use-media@1.4.0 requires a peer of react@^16.8.1 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN use-subscription@1.4.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
7:24:36 AM: npm WARN webp-loader@0.6.0 requires a peer of webpack-cli@* but none is installed. You must install peer dependencies yourself.
7:24:36 AM: removed 10 packages in 7.953s
7:24:37 AM: 139 packages are looking for funding
7:24:37 AM:   run `npm fund` for details
7:24:37 AM: NPM modules installed
7:24:37 AM: Started restoring cached go cache
7:24:37 AM: Finished restoring cached go cache
7:24:37 AM: go version go1.14.4 linux/amd64
7:24:37 AM: go version go1.14.4 linux/amd64
7:24:37 AM: Installing missing commands
7:24:37 AM: Verify run directory
7:24:38 AM: ​
7:24:38 AM: ┌─────────────────────────────┐
7:24:38 AM: │        Netlify Build        │
7:24:38 AM: └─────────────────────────────┘
7:24:38 AM: ​
7:24:38 AM: ❯ Version
7:24:38 AM:   @netlify/build 3.3.0
7:24:38 AM: ​
7:24:38 AM: ❯ Flags
7:24:38 AM:   deployId: 5f434efac86c107021dfb30c
7:24:38 AM:   mode: buildbot
7:24:38 AM: ​
7:24:38 AM: ❯ Current directory
7:24:38 AM:   /opt/build/repo
7:24:38 AM: ​
7:24:38 AM: ❯ Config file
7:24:38 AM:   No config file was defined: using default values.
7:24:38 AM: ​
7:24:38 AM: ❯ Context
7:24:38 AM:   production
7:24:38 AM: ​
7:24:38 AM: ❯ Loading plugins
7:24:38 AM:    - netlify-plugin-algolia-index@0.3.0 from Netlify app
7:24:38 AM:    - netlify-build-plugin-perfbeacon@1.0.3 from Netlify app
7:24:38 AM:    - netlify-build-plugin-speedcurve@1.0.5 from Netlify app
7:24:38 AM:    - netlify-plugin-checklinks@4.1.1 from Netlify app
7:24:38 AM:    - netlify-plugin-cache-nextjs@1.4.0 from Netlify app
7:24:38 AM:    - @netlify/plugin-sitemap@0.3.4 from Netlify app
7:24:44 AM: ​
7:24:44 AM: ┌────────────────────────────────────────────────────────┐
7:24:44 AM: │ 1. onPreBuild command from netlify-plugin-cache-nextjs │
7:24:44 AM: └────────────────────────────────────────────────────────┘
7:24:44 AM: ​
7:24:44 AM: No cache found for the .next folder at the location `.next/cache`
7:24:44 AM: ​
7:24:44 AM: (netlify-plugin-cache-nextjs onPreBuild completed in 238ms)
7:24:44 AM: ​
7:24:44 AM: ┌───────────────────────────────────┐
7:24:44 AM: │ 2. Build command from Netlify app │
7:24:44 AM: └───────────────────────────────────┘
7:24:44 AM: ​
7:24:44 AM: $ next build && next export
7:24:45 AM: warn  - You have enabled experimental feature(s).
7:24:45 AM: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
7:24:45 AM: Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
7:24:45 AM: Creating an optimized production build...
7:25:08 AM: Compiled successfully.
7:25:08 AM: 
7:25:08 AM: Automatically optimizing pages...
7:25:10 AM: Page                                                                  Size     First Load JS
7:25:10 AM: ┌ ● /                                                                 1.76 kB        43.5 kB
7:25:10 AM: ├   /_app                                                             2.37 kB        41.8 kB
7:25:10 AM: ├ ○ /404                                                              7.66 kB        49.4 kB
7:25:10 AM: └ ● /archive                                                          2.97 kB        44.7 kB
7:25:10 AM: + First Load JS shared by all                                         41.8 kB
7:25:10 AM:   ├ static/pages/_app.module.js                                       2.37 kB
7:25:10 AM:   ├ chunks/d4cd15122a90f354d17d5be8728935a36029cc83.9a6d70.module.js  8.39 kB
7:25:10 AM:   ├ chunks/f002f1d960789f0db3b72dc695a12a0334c891a3.253edc.module.js  9.45 kB
7:25:10 AM:   ├ chunks/f298be57b48060b5daf6924a806cb804059e9f48.c929e4.module.js  6.89 kB
7:25:10 AM:   ├ chunks/framework.75d98b.module.js                                 8.26 kB
7:25:10 AM:   ├ runtime/main.2b84ce.module.js                                     5.66 kB
7:25:10 AM:   └ runtime/webpack.a5e0d3.module.js                                  746 B
7:25:10 AM: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
7:25:10 AM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
7:25:10 AM: ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
7:25:11 AM: warn  - You have enabled experimental feature(s).
7:25:11 AM: warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
7:25:11 AM: > using build directory: /opt/build/repo/.next
7:25:11 AM:   copying "static build" directory
7:25:11 AM: > No "exportPathMap" found in "next.config.js". Generating map from "./pages"
7:25:11 AM:   launching 7 workers
7:25:11 AM: Exporting (0/3)
7:25:11 AM:   copying "public" directory
7:25:11 AM: Exporting (1/3)
7:25:11 AM: Exporting (2/3)
7:25:11 AM: Exporting (3/3)
7:25:11 AM: Export successful
7:25:11 AM: ​
7:25:11 AM: (build.command completed in 27.3s)
7:25:11 AM: ​
7:25:11 AM: ┌──────────────────────────────────────────────────────────┐
7:25:11 AM: │ 3. onPostBuild command from netlify-plugin-algolia-index │
7:25:11 AM: └──────────────────────────────────────────────────────────┘
7:25:11 AM: ​
7:25:12 AM: Search Index JSON generated at /searchIndex.json!
7:25:12 AM: ​
7:25:12 AM: (netlify-plugin-algolia-index onPostBuild completed in 302ms)
7:25:12 AM: ​
7:25:12 AM: ┌───────────────────────────────────────────────────────┐
7:25:12 AM: │ 4. onPostBuild command from netlify-plugin-checklinks │
7:25:12 AM: └───────────────────────────────────────────────────────┘
7:25:12 AM: ​
7:25:12 AM: ​
7:25:12 AM: ┌───────────────────────────────────────────────────┐
7:25:12 AM: │ Plugin "netlify-plugin-checklinks" internal error │
7:25:12 AM: └───────────────────────────────────────────────────┘
7:25:12 AM: ​
7:25:12 AM:   Error message
7:25:12 AM:   UnhandledRejection: a promise was rejected but not handled: TypeError: Cannot read property 'startsWith' of null
7:25:12 AM: ​
7:25:12 AM:   Plugin details
7:25:12 AM:   Package:        netlify-plugin-checklinks
7:25:12 AM:   Version:        4.1.1
7:25:12 AM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
7:25:12 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
7:25:12 AM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
7:25:12 AM: ​
7:25:12 AM:   Error location
7:25:12 AM:   In "onPostBuild" event in "netlify-plugin-checklinks" from Netlify app
7:25:12 AM:       at HtmlAnchor.get canonical [as canonical] (/opt/buildhome/.netlify-build-plugins/node_modules/assetgraph/lib/relations/Relation.js:278:24)
7:25:12 AM:       at HtmlAnchor.get crossorigin [as crossorigin] (/opt/buildhome/.netlify-build-plugins/node_modules/assetgraph/lib/relations/Relation.js:215:14)
7:25:12 AM:       at processAsset (/opt/buildhome/.netlify-build-plugins/node_modules/hyperlink/lib/index.js:640:25)
7:25:12 AM: ​
7:25:12 AM:   Resolved config
7:25:12 AM:   build:
7:25:12 AM:     command: next build && next export
7:25:12 AM:     commandOrigin: ui
7:25:12 AM:     publish: /opt/build/repo/out
7:25:12 AM:   plugins:
7:25:12 AM:     - inputs: {}
7:25:12 AM:       origin: ui
7:25:12 AM:       package: netlify-plugin-algolia-index
7:25:12 AM:     - inputs: {}
7:25:12 AM:       origin: ui
7:25:12 AM:       package: netlify-build-plugin-perfbeacon
7:25:12 AM:     - inputs: {}
7:25:12 AM:       origin: ui
7:25:12 AM:       package: netlify-build-plugin-speedcurve
7:25:12 AM:     - inputs: {}
7:25:12 AM:       origin: ui
7:25:12 AM:       package: netlify-plugin-checklinks
7:25:12 AM:     - inputs: {}
7:25:12 AM:       origin: ui
7:25:12 AM:       package: netlify-plugin-cache-nextjs
7:25:12 AM:     - inputs: {}
7:25:12 AM:       origin: ui
7:25:12 AM:       package: '@netlify/plugin-sitemap'
7:25:12 AM: Caching artifacts
7:25:12 AM: Started saving node modules
7:25:12 AM: Finished saving node modules
7:25:12 AM: Started saving build plugins
7:25:12 AM: Finished saving build plugins
7:25:12 AM: Started saving pip cache
7:25:12 AM: Finished saving pip cache
7:25:12 AM: Started saving emacs cask dependencies
7:25:12 AM: Finished saving emacs cask dependencies
7:25:12 AM: Started saving maven dependencies
7:25:12 AM: Finished saving maven dependencies
7:25:12 AM: Started saving boot dependencies
7:25:12 AM: Finished saving boot dependencies
7:25:12 AM: Started saving go dependencies
7:25:12 AM: Finished saving go dependencies
7:25:12 AM: Error running command: Build script returned non-zero exit code: 1
7:25:12 AM: Failing build: Failed to build site
7:25:12 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
7:25:12 AM: Finished processing build request in 1m0.023555602s
```

The git commit that triggered this build is [here](https://github.com/ngoantho/anthonyngo.me/commit/19111845cabb4431237f9587e64786c2f9f82869).

Do you know what happened?

**Comment by bartbrosens** [comment]
3:03:12 PM: ────────────────────────────────────────────────────────────────
3:03:12 PM:   Plugin "netlify-plugin-checklinks" internal error             
3:03:12 PM: ────────────────────────────────────────────────────────────────
3:03:12 PM: ​
3:03:12 PM:   Error message
3:03:12 PM:   UnhandledRejection: a promise was rejected but not handled: TypeError: Cannot read property 'startsWith' of null

This error occurs on the build of a Hugo site once I enable the checklinks plugin. It happens all the time. I've tried some non-default entryPoints settings but this only resulted in 0 tests being run when I choose a non-existing entry-point.

Can I enable more debug output to check why this fails? Any other pointers how to resolve this?

The following is my `netlify.toml` file:
```
[build.environment]
  HUGO_VERSION = "0.74.3"

[build]
  publish = "public/"

[context.production]
  command = "hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "public, max-age=600, must-revalidate"
    referrer-policy = "strict-origin-when-cross-origin"
    x-frame-options = "DENY"

[context.deploy-preview]
  command = "hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[[plugins]]
package = "netlify-plugin-checklinks"
```

Full Netlify deploy log:
```
3:02:41 PM: Build ready to start
3:02:43 PM: build-image version: 53b83b6bede2920f236b25b6f5a95334320dc849
3:02:43 PM: build-image tag: v3.6.0
3:02:43 PM: buildbot version: 8ae026ef4905d9174e416775c6b64aa19950569b
3:02:43 PM: Fetching cached dependencies
3:02:43 PM: Starting to download cache of 327.6MB
3:02:44 PM: Finished downloading cache in 1.399035818s
3:02:44 PM: Starting to extract cache
3:02:50 PM: Finished extracting cache in 5.909210449s
3:02:50 PM: Finished fetching cache in 7.401432249s
3:02:50 PM: Starting to prepare the repo for build
3:02:52 PM: Preparing Git Reference merge-requests/110/head
3:02:57 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
3:02:57 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL' versus 'hugo' in the Netlify UI
3:02:57 PM: Starting build script
3:02:57 PM: Installing dependencies
3:02:57 PM: Python version set to 2.7
3:02:58 PM: Started restoring cached node version
3:03:01 PM: Finished restoring cached node version
3:03:02 PM: v12.18.0 is already installed.
3:03:02 PM: Now using node v12.18.0 (npm v6.14.4)
3:03:02 PM: Started restoring cached build plugins
3:03:02 PM: Finished restoring cached build plugins
3:03:03 PM: Attempting ruby version 2.7.1, read from environment
3:03:04 PM: Using ruby version 2.7.1
3:03:04 PM: Using PHP version 5.6
3:03:04 PM: Installing Hugo 0.74.3
3:03:04 PM: Hugo Static Site Generator v0.74.3-DA0437B4/extended linux/amd64 BuildDate: 2020-07-23T16:30:30Z
3:03:04 PM: Started restoring cached go cache
3:03:04 PM: Finished restoring cached go cache
3:03:04 PM: go version go1.14.4 linux/amd64
3:03:04 PM: go version go1.14.4 linux/amd64
3:03:04 PM: Installing missing commands
3:03:04 PM: Verify run directory
3:03:06 PM: ​
3:03:06 PM: ────────────────────────────────────────────────────────────────
3:03:06 PM:   Netlify Build                                                 
3:03:06 PM: ────────────────────────────────────────────────────────────────
3:03:06 PM: ​
3:03:06 PM: ❯ Version
3:03:06 PM:   @netlify/build 8.0.0
3:03:06 PM: ​
3:03:06 PM: ❯ Flags
3:03:06 PM:   deployId: 5ff32001ce812000086b73ca
3:03:06 PM:   mode: buildbot
3:03:06 PM: ​
3:03:06 PM: ❯ Current directory
3:03:06 PM:   /opt/build/repo
3:03:06 PM: ​
3:03:06 PM: ❯ Config file
3:03:06 PM:   /opt/build/repo/netlify.toml
3:03:06 PM: ​
3:03:06 PM: ❯ Context
3:03:06 PM:   deploy-preview
3:03:06 PM: ​
3:03:06 PM: ❯ Loading plugins
3:03:06 PM:    - netlify-plugin-checklinks@4.1.1 from netlify.toml
3:03:08 PM: ​
3:03:08 PM: ────────────────────────────────────────────────────────────────
3:03:08 PM:   1. build.command from netlify.toml                            
3:03:08 PM: ────────────────────────────────────────────────────────────────
3:03:08 PM: ​
3:03:08 PM: $ hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL
3:03:12 PM: Building sites …
3:03:12 PM:                    | EN
3:03:12 PM: -------------------+------
3:03:12 PM:   Pages            | 712
3:03:12 PM:   Paginator pages  |   0
3:03:12 PM:   Non-page files   |   0
3:03:12 PM:   Static files     | 988
3:03:12 PM:   Processed images |   0
3:03:12 PM:   Aliases          |   0
3:03:12 PM:   Sitemaps         |   1
3:03:12 PM:   Cleaned          |   0
3:03:12 PM: Total in 3416 ms
3:03:12 PM: ​
3:03:12 PM: (build.command completed in 3.5s)
3:03:12 PM: ​
3:03:12 PM: ────────────────────────────────────────────────────────────────
3:03:12 PM:   2. onPostBuild command from netlify-plugin-checklinks         
3:03:12 PM: ────────────────────────────────────────────────────────────────
3:03:12 PM: ​
3:03:12 PM: ​
3:03:12 PM: ────────────────────────────────────────────────────────────────
3:03:12 PM:   Plugin "netlify-plugin-checklinks" internal error             
3:03:12 PM: ────────────────────────────────────────────────────────────────
3:03:12 PM: ​
3:03:12 PM:   Error message
3:03:12 PM:   UnhandledRejection: a promise was rejected but not handled: TypeError: Cannot read property 'startsWith' of null
3:03:12 PM: ​
3:03:12 PM:   Plugin details
3:03:12 PM:   Package:        netlify-plugin-checklinks
3:03:12 PM:   Version:        4.1.1
3:03:12 PM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
3:03:12 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
3:03:12 PM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
3:03:12 PM: ​
3:03:12 PM:   Error location
3:03:12 PM:   In "onPostBuild" event in "netlify-plugin-checklinks" from netlify.toml
3:03:12 PM:       at HtmlAnchor.get canonical [as canonical] (/opt/build/repo/.netlify/plugins/node_modules/assetgraph/lib/relations/Relation.js:278:24)
3:03:12 PM:       at HtmlAnchor.get crossorigin [as crossorigin] (/opt/build/repo/.netlify/plugins/node_modules/assetgraph/lib/relations/Relation.js:215:14)
3:03:12 PM:       at processAsset (/opt/build/repo/.netlify/plugins/node_modules/hyperlink/lib/index.js:647:25)
3:03:12 PM: ​
3:03:12 PM:   Resolved config
3:03:12 PM:   build:
3:03:12 PM:     command: hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL
3:03:12 PM:     commandOrigin: config
3:03:12 PM:     environment:
3:03:12 PM:       - REVIEW_ID
3:03:12 PM:       - HUGO_VERSION
3:03:12 PM:     publish: /opt/build/repo/public
3:03:12 PM:   headers:
3:03:12 PM:     - for: /*      values:        cache-control: 'public, max-age=600, must-revalidate'        referrer-policy: strict-origin-when-cross-origin        x-frame-options: DENY  plugins:    - inputs: {}      origin: config      package: netlify-plugin-checklinksCaching artifacts
3:03:12 PM: Started saving build plugins
3:03:12 PM: Finished saving build plugins
3:03:12 PM: Started saving pip cache
3:03:12 PM: Finished saving pip cache
3:03:12 PM: Started saving emacs cask dependencies
3:03:12 PM: Finished saving emacs cask dependencies
3:03:12 PM: Started saving maven dependencies
3:03:12 PM: Finished saving maven dependencies
3:03:12 PM: Started saving boot dependencies
3:03:12 PM: Finished saving boot dependencies
3:03:12 PM: Started saving rust rustup cache
3:03:13 PM: Finished saving rust rustup cache
3:03:13 PM: Started saving rust cargo bin cache
3:03:13 PM: Finished saving rust cargo bin cache
3:03:13 PM: Started saving go dependencies
3:03:13 PM: Finished saving go dependencies
3:03:13 PM: Build failed due to a plugin error: Build script returned non-zero exit code: 3
3:03:13 PM: Failing build: Failed to build site
3:03:13 PM: Failed during stage 'building site': Build script returned non-zero exit code: 3
3:03:13 PM: Finished processing build request in 30.109795901s
```
