### ISSUE TITLE
Check fails when "checkExternal = true" (Cannot read property 'querySelectorAll' of undefined)

### ISSUE THREAD

**Issue by philippederyck** [Munter/netlify-plugin-checklinks#209]
The plugin works as expected with checkExternal set to false. The check completes in 8s (see snippet 1 below).

With checkExternal set to true, the check hangs initially, then shows a green dotted line, and then bails with an error (see snippet 2 below).

The site I'm running this on is a Jekyll build of [https://pragmaticwebsecurity.com](https://pragmaticwebsecurity.com) (the currently published version).

Any idea what may go wrong?

__*Successful check (checkExternal=false)*__
```
8:05:07 AM: ┌───────────────────────────────────────────────────────┐
8:05:07 AM: │ 2. onPostBuild command from netlify-plugin-checklinks │
8:05:07 AM: └───────────────────────────────────────────────────────┘
8:05:07 AM: ​
8:05:16 AM: .,....................................................................................................................................................................................................................................
8:05:16 AM:   230 tests
8:05:16 AM:     1 skipped
8:05:16 AM:   230 passed
8:05:16 AM: ​
8:05:16 AM: (netlify-plugin-checklinks onPostBuild completed in 8.8s)
```

__*Failed check (checkExternal=true)*__
```
8:07:26 AM: ┌───────────────────────────────────────────────────────┐
8:07:26 AM: │ 2. onPostBuild command from netlify-plugin-checklinks │
8:07:26 AM: └───────────────────────────────────────────────────────┘
8:07:26 AM: ​
8:10:59 AM: .,..............................................................................................................................................................................................................×.............................×..........................................................................................................×.......................××...............................×...........×.........××.................×.×......×...................................................................................................................××..........×.......................××............................................................................................................×...........................................................................................................................×............................×..............................................×.×.×.××××××............×.×......×...................××.×.×××.×××××.××.××..×..×.×.×...×...................×...×.××...........................×.........×..........×.....×.................................×.×..×.....×.×....×....×..........×...×...××..×...×..×.×.....×.×......×××.×..××.×..××.........×.....×.×.×.×.×.××.×.×.×....××.........×...×..×.×.....×.×.×.×..××.......×.×.×..×.×.××××××××××.×...×.××.×..××..××.×...×......×....××..............×.×....×.×.×.××.×..........×.×.×.×....×........................×.××.×.×.×....×...×.×....×..×..............××...........×.××....×...×........×......×..×××.×..×..........×........×...×..×.×.×................×..×...×..×..×.×.×..........×.....×..×.××..×.×.....×.×.×..×......×.××.×.×.×.××.....×.×.......××..××.×....×....×...×..........×.×.×.××...×...×........×..×.×....×...........................................................×...×..×.×.×.×.×.....×.......×..×.×...×.×.×.....×........×........×..×...×.......×...×.....×...............................................................................................................×..×...×..×...×.......×.×..×....×...×.............×.×.×××××..×.×..........×..×.×..×××...××...........×..××...×××××......×..×...×××.......×.......×.....×.....×...×.....................××××××××.×.×..××..×..×.×.×..×.................×××..×........................×.×....................................×......×.×.....×........×....××××××××........×..×...×...................××..×...×....×.....×.××.........×.×...×.........×.×××.×.....×..×...×.×..×..×............×....×..×.×..×.×..×.....×............×.×.×.×.×...................×.×..×.×...×...........×.....×.....×..×.×.×.×.×.×.×....×.......×.××.×.×.××××..×.×.×.×..........×.....×..×.×.×.×.×...×..×.×...×.........×.×.××.×.×...×××..×...×.......×.×...×..×.×.×.×.×.×.×.×...××××××××××.×...×..........×.×.×.××××××.........×.×.×.×....×...×..×.×.×.×.×.×.×××××××××.×...............××..×.×.×.×.×.×.×.××××.........×.......×..×.×.×.×.×.×.×.××××××××.××.................×.×.×.××.×.×.....×××.×..×..×..×.....×....×.×..×
8:12:50 AM: 92m.×.××.×.×.×.×.×..×..×..×......×...×..××.×.×.×.×..××..×.......................................................×....×..×.×××.×.××..×.......................××......×.........×................................................×......×..×.×...×...×.×...×.×.×.×.×..×....×..×.×....×.×....×.×..×..×......×....×........×............×...................×........................................................×.......................×.......................×......×..×...×.×...×....×...×..×....×.×..××......................×........×....×........×.×................××.×....×××.×..×...××.×.××.××.××××...××.××..××.×.×.....×....×..........×..............................×.....×...××.×.......×..................×...........×..×...×.×.×.×.×.×....×.×.×..×......×.×....×..×.×..×.×..×.×.×.×.×......×..×..×....×.×.×.×.×.×.×.×..×.×.×.×............×..×...×..............×...........................×....×..×.×.×.××××××××××.××.×.×.×××..×.×.×.××...×.×..×..××..××.....×.......×..×.×.×.×.×.×.×..×..........×.×.×.×.×.×.×.×.×.................×.×..×....×..×....×...×...×....×...×.....×.×.×.×.×.×......×.×......×.×.............×...×..×.×.×.×.×.×.×....×.×..×..........×.×.×..×..×..×.×.×.×.×.×.×.×..×................×.×.×.×.×.××.×.×................×.×.×.×.×.×.×..×..×..............×.×.×.×.×.×...........................................×...×.........×.......×...×...×..×.×.×.×.........×.×...........×..×....×...×......×.......×......×..×..×..×.×..×...×​
8:12:50 AM: ┌───────────────────────────────────────────────────┐
8:12:50 AM: │ Plugin "netlify-plugin-checklinks" internal error │
8:12:50 AM: └───────────────────────────────────────────────────┘
8:12:50 AM: ​
8:12:50 AM:   Error message
8:12:50 AM:   UnhandledRejection: a promise was rejected but not handled: TypeError: Cannot read property 'querySelectorAll' of undefined
8:12:50 AM: ​
8:12:50 AM:   Plugin details
8:12:50 AM:   Package:        netlify-plugin-checklinks
8:12:50 AM:   Version:        4.1.1
8:12:50 AM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
8:12:50 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
8:12:50 AM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
8:12:50 AM: ​
8:12:50 AM:   Error location
8:12:50 AM:   In "onPostBuild" event in "netlify-plugin-checklinks" from netlify.toml
8:12:50 AM:       at processAsset (/opt/buildhome/.netlify-build-plugins/node_modules/hyperlink/lib/index.js:532:27)
8:12:50 AM:       at runMicrotasks (<anonymous>)
8:12:50 AM:       at runNextTicks (internal/process/task_queues.js:62:5)
8:12:50 AM:       at processImmediate (internal/timers.js:429:9)
```

**Comment by Munter** [comment]
That doesn't look good. Definitely a bug. Is this webpage public? Then I can probably recreate the situation from my end

**Comment by philippederyck** [comment]
Yep, this is the public website running on [https://pragmaticwebsecurity.com](https://pragmaticwebsecurity.com)

**Comment by rstavchansky** [comment]
Although we're not getting the same error, setting checkExternal to true results in a build timeout on Netlify for our site. I figured it may help to comment on a similar issue. The site doesn't have a public repo, but the output is at https://docs.netlify.com/. 😄

I did try to reproduce this on a public repo, but the test actually showed that checkExternal = true worked on that repo with plain HTML.

**Comment by Maximization** [comment]
I get the same error for https://maximorlov.com

```
6:35:20 PM: ────────────────────────────────────────────────────────────────
6:35:20 PM:   2. netlify-plugin-checklinks (onPostBuild event)              
6:35:20 PM: ────────────────────────────────────────────────────────────────
6:35:20 PM: ​
6:37:14 PM: .............................................................................×××.............................................×.....................×.......×××.×....................................................................................................................................................................................................................................................................................................×××..............................××××××××.......................................................................................................×...................................​
6:37:14 PM: ────────────────────────────────────────────────────────────────
6:37:14 PM:   Plugin "netlify-plugin-checklinks" internal error             
6:37:14 PM: ────────────────────────────────────────────────────────────────
6:37:14 PM: ​
6:37:14 PM:   Error message
6:37:14 PM:   UnhandledRejection: a promise was rejected but not handled: TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
6:37:14 PM: ​
6:37:14 PM:   Plugin details
6:37:14 PM:   Package:        netlify-plugin-checklinks
6:37:14 PM:   Version:        4.1.1
6:37:14 PM:   Repository:     git://github.com/munter/netlify-plugin-checklinks.git
6:37:14 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-checklinks
6:37:14 PM: Creating deploy upload records
6:37:14 PM:   Report issues:  https://github.com/munter/netlify-plugin-checklinks/issues
6:37:14 PM: ​
6:37:14 PM:   Error location
6:37:14 PM:   In "onPostBuild" event in "netlify-plugin-checklinks" from netlify.toml and package.json
6:37:14 PM: Failed during stage 'building site': Build script returned non-zero exit code: 3 (https://ntl.fyi/exit-code-3)
6:37:14 PM:       at processAsset (/opt/build/repo/node_modules/hyperlink/lib/index.js:535:27)
6:37:14 PM:       at runNextTicks (node:internal/process/task_queues:61:5)
6:37:14 PM:       at processImmediate (node:internal/timers:437:9)
```

**Comment by Maximization** [comment]
Tested with fix from https://github.com/Munter/netlify-plugin-checklinks/pull/571 on my site and it works

**Comment by artberger** [comment]
After enabling the checklinks plug-in, my deploy builds fail with the same error:
```
UnhandledRejection: a promise was rejected but not handled: TypeError: Cannot read properties of undefined (reading 'querySelectorAll')`
```
